#!/bin/bash

# Copyright 2014 Markus Lux

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

SCRIPT_DIR="$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd -P )"

if [[ -f "$SCRIPT_DIR/config" ]]; then
	. "$SCRIPT_DIR/config"
else
	echo "In order to use passman, you need to set configuration options in the file $SCRIPT_DIR/config"
	exit 1
fi

if [[ ! -f "$PASS_FILE" ]]; then
	echo "Password file $PASS_FILE not found!"
	exit 1
fi

if [[ -z "$PASS_LENGTH" ]]; then
	PASS_LENGTH='15'
fi

# Returns all keys present in the password file.
function getkeys
{
    gpg --no-tty --quiet -q -d "$PASS_FILE" | cut -f 1 | sort
}

# Returns all keys and additionally auto-type hints if present
function getkeyshints
{
    gpg --no-tty --quiet -q -d "$PASS_FILE" | cut -f 1,4 | sort
}

# Gets a login as a string "user<TAB>pass".
# First argument: entry key
function get
{
    local key="$1"
    if [[ -n "$key" ]]; then
        if [[ -z "$ONLY_PW" ]]; then
            gpg --no-tty --quiet -q -d "$PASS_FILE" | grep -P "^$key\t" | cut -f 2,3
        else
            gpg --no-tty --quiet -q -d "$PASS_FILE" | grep -P "^$key\t" | cut -f 3
        fi
    fi
}

# Gets the hint for a login.
# First argument: entry key
function gethint
{
    local key="$1"
    if [[ -n "$key" ]]; then
        gpg --no-tty --quiet -q -d "$PASS_FILE" | grep -P "^$key\t" | cut -f 4
    fi
}

# Adds an entry to the password file.
function add
{

	IFS= read -r -p "Identifier: " site
	local site=$(echo "$site" | sed -e 's/^ *//g' -e 's/ *$//g') # remove leading/trailing whitespaces
	if [[ -z "$site" ]]; then
		echo "Please specify a site identifier."
		exit 1
	fi

	IFS= read -p "Username (optional): " user
	IFS= read -r -s -p "Password (will not be echoed): " pass
	echo

	echo -e "$site$user$pass" | grep -P '\t' > /dev/null
	if [[ $? -eq 0 ]]; then
		echo "All values must NOT contain any <TAB> characters."
		exit 1
	fi

    if [[ -z "$pass" ]]; then
        local pass=$(pwgen -s1 "$PASS_LENGTH")
        echo "Generated password for $user: $pass"
    fi

    local line="$site\\t$user\\t$pass"

    local passes=$(gpg --no-tty --quiet -d "$PASS_FILE")

    if [[ $? -eq 0 ]]; then
        passes+='\n'
        passes+="$line"
        echo -e "$passes" | gpg $GPG_OPTS --output "$PASS_FILE"
    fi
}

# Deletes an entry from the password file
# First argument: entry key
function del
{
    local key="$1"
    if [[ -n "$key" ]]; then
        passes=$(gpg --no-tty --quiet -d "$PASS_FILE" | sed "/^$key	/d")

        if [[ $? -eq 0 ]]; then
            echo -e "$passes" | gpg $GPG_OPTS --output "$PASS_FILE"
        fi
    fi
}

# Set auto type hint for specific entry
# First argument: entry key
# Second argument: hint to set
function sethint
{
    local key="$1"
    local hint="$2"
    if [[ -n "$key" ]]; then
        local login=$(get "$key")

        if [[ -z "$login" ]]; then
            echo "Key '$key' not found."
            return
        fi

        if [[ -z "$hint" ]]; then
            echo "No regex specified."
            return
        fi

        local user=${login%	*}
        local password=${login#*	}

        local regex=$(echo "$hint" | tr -d '\t')
        local line="$key\\t$user\\t$password\\t$regex"

        local passes=$(gpg --no-tty --quiet -d "$PASS_FILE" | sed "/^$key	/d")

        if [[ $? -eq 0 ]]; then
            passes+='\n'
            passes+="$line"
            echo -e "$passes" | gpg $GPG_OPTS --output "$PASS_FILE"
        fi
    fi
}

# Types the credentials as user<TAB>password<enter>.
# First argument : user
# Second argument: password
function autotype
{
    local user="$1"
    local password="$2"
    if [[ -n "$user" ]] && [[ -z "$ONLY_PW" ]]; then
        xdotool type --delay 50 -- "$user"
        xdotool key Tab
    fi
    xdotool type --delay 50 -- "$password"
    xdotool key Return
}

# Fills credentials by selecting the desired site with dmenu in a (e.g. browser) form
# First argument : site to submit (optional)
# If first argument is empty, dmenu will pop up
function submitform
{
    local key
    if [[ -n "$1" ]]; then
        key="$1"
    else
        keys=$(getkeys)
        key=$(echo "$keys" | dmenu -p "Select:")
    fi

    local login=$(get "$key")

    if [[ -z "$login" ]]; then
        return
    fi

    local user=${login%	*}
    local password=${login#*	}

    autotype "$user" "$password"
}

# Try to match site key against current window name
# If one key matches, the credentials will auto-type automatically
# If more than one key matches, dmenu pops up to choose between them
# If no key matches, standard dmenu will pop up
function autosubmitform
{
    local windowname=$(xdotool getwindowfocus getwindowname)

    local keyshints=$(getkeyshints)

    local matches=()
    OLDIFS="$IFS"; IFS=$'\n'
    for keyhint in $keyshints; do
        local key=${keyhint%	*}
        local hint=${keyhint#*	}

        if [[ -z "$hint" ]]; then
            hint="$key"
        fi

        echo "$windowname" | grep -Ei "$hint" > /dev/null
        if [[ $? -eq 0 ]]; then
            matches+=( "$key" )
        fi
    done
    IFS="$OLDIFS"

    local numMatches=${#matches[@]};

    case $numMatches in
        0)
            submitform
            ;;
        1)
            submitform "${matches[0]}"
            ;;
        *)
            # trick the IFS to output array items as separate lines for dmenu
            local OLDIFS="$IFS"; IFS=$'\n'
            local key=$(echo "${matches[*]}" | dmenu -p "Select:")
            IFS="$OLDIFS"
            if [[ -z "$key" ]]; then
                return;
            fi
            submitform "$key"
            ;;
    esac
}

# Call "passman onlypw <action> <params>" as you would call passman normally with "passman <action> <params>"
# This will only type the password without username.
function onlypw
{
    export ONLY_PW=1
    eval "$@"
}



# Set up GPG identity. Use symmetric cipher if $GPG_IDENTITY has not been set.
if [[ -z "$GPG_IDENTITY" ]]; then
    GPG_OPTS='--yes --symmetric --cipher-algo AES256'
else
    GPG_OPTS="--yes --encrypt --recipient $GPG_IDENTITY"
fi

# This has to be done to allow empty parameters (e.g. for user-less logins).
params=''
for i in "$@"
do
params="$params '$i'"
done

# The script parameters determine which method gets called.
eval "$params"
